import { z } from "zod";
import tokens from "./tokens.json" with { type: "json" };

export const SCHEMA_VERSION = 1 as const;

export const paletteSchema = z.object({
  id: z.string().regex(/^[a-z0-9-]+$/),
  name: z.string().min(1).max(64),
  colors: z
    .array(z.string().regex(/^#[0-9A-Fa-f]{6}$/))
    .min(2)
    .max(8),
});

export const brandTokensSchema = z.object({
  schemaVersion: z.literal(SCHEMA_VERSION),
  name: z.string().min(1).max(64),
  typography: z.object({
    display: z.string().min(1).max(128),
    editorial: z.string().min(1).max(128),
    mono: z.string().min(1).max(128),
    pixel: z.string().min(1).max(128),
  }),
  palettes: z.array(paletteSchema).min(1),
});

export const renderDimensionsSchema = z.object({
  width: z.number().int().min(320).max(7680).default(3840),
  height: z.number().int().min(180).max(4320).default(2160),
  fps: z.number().min(1).max(120).default(30),
  durationSeconds: z.number().min(0.1).max(60).default(5),
});

export const mapJobRequestSchema = z
  .object({
    schemaVersion: z.literal(SCHEMA_VERSION),
    kind: z.literal("map"),
    countries: z.array(z.string().length(3).toUpperCase()).min(1).max(24),
    animation: z.enum([
      "fly-to",
      "pan-between",
      "border-draw",
      "fill-reveal",
      "pulse-highlight",
    ]),
    projection: z
      .enum(["natural-earth", "mercator", "orthographic"])
      .default("natural-earth"),
    labels: z.boolean().default(true),
    transparent: z.boolean().default(true),
    paletteId: z.string().default("moneymoves-core"),
    outputName: z
      .string()
      .regex(/^[a-zA-Z0-9][a-zA-Z0-9._-]*$/)
      .default("moneymoves-map.mov"),
  })
  .merge(renderDimensionsSchema);

export const asciiTitleJobRequestSchema = z
  .object({
    schemaVersion: z.literal(SCHEMA_VERSION),
    kind: z.literal("ascii-title"),
    text: z.string().min(1).max(160),
    font: z
      .enum(["Standard", "Slant", "Big", "Small", "Block"])
      .default("Standard"),
    animation: z
      .enum(["static", "reveal", "flicker", "scramble"])
      .default("reveal"),
    paletteId: z.string().default("terminal"),
    outputName: z
      .string()
      .regex(/^[a-zA-Z0-9][a-zA-Z0-9._-]*$/)
      .default("moneymoves-ascii.mov"),
  })
  .merge(renderDimensionsSchema);

export const renderJobRequestSchema = z.discriminatedUnion("kind", [
  mapJobRequestSchema,
  asciiTitleJobRequestSchema,
]);

export const jobStateSchema = z.enum([
  "queued",
  "running",
  "complete",
  "failed",
  "cancelled",
]);

export const renderJobSchema = z.object({
  id: z.string().uuid(),
  state: jobStateSchema,
  kind: z.enum(["map", "ascii-title"]),
  progress: z.number().min(0).max(1),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
  outputPath: z.string().optional(),
  error: z.string().optional(),
});

export const effectPresetSchema = z.object({
  id: z.string().regex(/^[a-z0-9-]+$/),
  name: z.string().min(1).max(80),
  matchName: z.string().startsWith("com.moneymoves."),
  parameters: z.record(
    z.string(),
    z.union([z.number(), z.boolean(), z.string()]),
  ),
});

export type Palette = z.infer<typeof paletteSchema>;
export type BrandTokens = z.infer<typeof brandTokensSchema>;
export type MapJobRequest = z.infer<typeof mapJobRequestSchema>;
export type AsciiTitleJobRequest = z.infer<typeof asciiTitleJobRequestSchema>;
export type RenderJobRequest = z.infer<typeof renderJobRequestSchema>;
export type RenderJob = z.infer<typeof renderJobSchema>;
export type EffectPreset = z.infer<typeof effectPresetSchema>;

export const effectParameterTypeSchema = z.enum([
  "number",
  "boolean",
  "select",
  "color",
  "point",
  "bitmask",
]);

export const effectParameterOptionSchema = z.object({
  id: z.string().regex(/^[a-z0-9-]+$/),
  label: z.string().min(1).max(64),
  value: z.union([z.number(), z.string(), z.boolean()]),
});

export const effectParameterDefinitionSchema = z.object({
  key: z.string().regex(/^[a-z][a-zA-Z0-9]*$/),
  label: z.string().min(1).max(80),
  index: z.number().int().positive(),
  type: effectParameterTypeSchema,
  defaultValue: z.union([z.number(), z.string(), z.boolean()]),
  min: z.number().optional(),
  max: z.number().optional(),
  step: z.number().positive().optional(),
  unit: z.enum(["pixels", "degrees", "percent", "frames"]).optional(),
  options: z.array(effectParameterOptionSchema).optional(),
  keyframeable: z.boolean().default(true),
  bitCountParameter: z.string().optional(),
});

export const effectDefinitionSchema = z.object({
  id: z.string().regex(/^[a-z0-9-]+$/),
  name: z.string().min(1).max(80),
  matchName: z.string().startsWith("com.moneymoves."),
  category: z.enum(["transition", "palette", "stylize", "advanced"]),
  status: z.enum(["available", "planned"]),
  description: z.string().min(1).max(180),
  parameters: z.array(effectParameterDefinitionSchema),
  presets: z.array(effectPresetSchema).default([]),
  schemaVersion: z.literal(SCHEMA_VERSION),
});

export const effectRegistrySchema = z.array(effectDefinitionSchema);

export type EffectParameterDefinition = z.infer<
  typeof effectParameterDefinitionSchema
>;
export type EffectDefinition = z.infer<typeof effectDefinitionSchema>;

export const brandTokens = brandTokensSchema.parse(tokens);

const EFFECT_PALETTE_OPTIONS = [
  { id: "custom", label: "Custom", value: 1 },
  { id: "moneymoves-core", label: "MoneyMoves Core", value: 2 },
  { id: "editorial-mono", label: "Editorial Mono", value: 3 },
  { id: "signal-blue", label: "Signal Blue", value: 4 },
  { id: "terminal", label: "Terminal", value: 5 },
  { id: "phosphor", label: "Phosphor", value: 6 },
  { id: "amber", label: "Amber", value: 7 },
  { id: "paper", label: "Paper", value: 8 },
] as const;

const EIGHT_BIT_COLOR_DEFAULTS = [
  "#FF2448",
  "#0B0B70",
  "#FFF6D8",
  "#39E39D",
  "#FFCC28",
  "#F229D4",
  "#080808",
  "#3D8BFF",
] as const;

export const FRAME_GATE_PRESETS: readonly EffectPreset[] = [
  {
    id: "throttle-in",
    name: "Throttle In",
    matchName: "com.moneymoves.frame-gate",
    parameters: {
      mode: "head",
      headLength: 5,
      headMask: 21,
      tailLength: 5,
      tailMask: 21,
    },
  },
  {
    id: "throttle-out",
    name: "Throttle Out",
    matchName: "com.moneymoves.frame-gate",
    parameters: {
      mode: "tail",
      headLength: 5,
      headMask: 21,
      tailLength: 5,
      tailMask: 21,
    },
  },
  {
    id: "throttle-both",
    name: "Throttle Both",
    matchName: "com.moneymoves.frame-gate",
    parameters: {
      mode: "both",
      headLength: 5,
      headMask: 21,
      tailLength: 5,
      tailMask: 21,
    },
  },
  {
    id: "hard-stutter",
    name: "Hard Stutter",
    matchName: "com.moneymoves.frame-gate",
    parameters: {
      mode: "both",
      headLength: 8,
      headMask: 85,
      tailLength: 8,
      tailMask: 85,
    },
  },
];

export const EFFECT_REGISTRY: readonly EffectDefinition[] =
  effectRegistrySchema.parse([
    {
      id: "frame-gate",
      name: "Frame Gate",
      matchName: "com.moneymoves.frame-gate",
      category: "transition",
      status: "available",
      description:
        "Transparent throttle and stutter frames without touching audio.",
      parameters: [
        {
          key: "mode",
          label: "Region",
          index: 1,
          type: "select",
          defaultValue: 3,
          options: [
            { id: "head", label: "Start", value: 1 },
            { id: "tail", label: "End", value: 2 },
            { id: "both", label: "Start + End", value: 3 },
          ],
          keyframeable: false,
        },
        {
          key: "headLength",
          label: "Start frames",
          index: 2,
          type: "number",
          defaultValue: 5,
          min: 1,
          max: 12,
          step: 1,
          unit: "frames",
          keyframeable: false,
        },
        {
          key: "headMask",
          label: "Start pattern",
          index: 3,
          type: "bitmask",
          defaultValue: 21,
          min: 0,
          max: 4095,
          bitCountParameter: "headLength",
          keyframeable: false,
        },
        {
          key: "tailLength",
          label: "End frames",
          index: 4,
          type: "number",
          defaultValue: 5,
          min: 1,
          max: 12,
          step: 1,
          unit: "frames",
          keyframeable: false,
        },
        {
          key: "tailMask",
          label: "End pattern",
          index: 5,
          type: "bitmask",
          defaultValue: 21,
          min: 0,
          max: 4095,
          bitCountParameter: "tailLength",
          keyframeable: false,
        },
      ],
      presets: [...FRAME_GATE_PRESETS],
      schemaVersion: SCHEMA_VERSION,
    },
    {
      id: "rgb-shift",
      name: "RGB Shift",
      matchName: "com.moneymoves.rgb-shift",
      category: "palette",
      status: "available",
      description:
        "Deterministic per-channel displacement with preserved alpha.",
      parameters: [
        {
          key: "amount",
          label: "Amount",
          index: 1,
          type: "number",
          defaultValue: 12,
          min: 0,
          max: 200,
          step: 1,
          unit: "pixels",
          keyframeable: true,
        },
        {
          key: "direction",
          label: "Direction",
          index: 2,
          type: "number",
          defaultValue: 0,
          min: 0,
          max: 360,
          step: 1,
          unit: "degrees",
          keyframeable: true,
        },
        {
          key: "redOffset",
          label: "Red offset",
          index: 3,
          type: "number",
          defaultValue: 1,
          min: -2,
          max: 2,
          step: 0.01,
          keyframeable: true,
        },
        {
          key: "greenOffset",
          label: "Green offset",
          index: 4,
          type: "number",
          defaultValue: 0,
          min: -2,
          max: 2,
          step: 0.01,
          keyframeable: true,
        },
        {
          key: "blueOffset",
          label: "Blue offset",
          index: 5,
          type: "number",
          defaultValue: -1,
          min: -2,
          max: 2,
          step: 0.01,
          keyframeable: true,
        },
        {
          key: "mix",
          label: "Mix",
          index: 6,
          type: "number",
          defaultValue: 1,
          min: 0,
          max: 1,
          step: 0.01,
          unit: "percent",
          keyframeable: true,
        },
        {
          key: "edgeBehavior",
          label: "Edges",
          index: 7,
          type: "select",
          defaultValue: 1,
          options: [
            { id: "clamp", label: "Clamp", value: 1 },
            { id: "mirror", label: "Mirror", value: 2 },
            { id: "wrap", label: "Wrap", value: 3 },
          ],
          keyframeable: false,
        },
      ],
      presets: [
        {
          id: "subtle-split",
          name: "Subtle Split",
          matchName: "com.moneymoves.rgb-shift",
          parameters: { amount: 5, direction: 0, mix: 0.7 },
        },
        {
          id: "money-split",
          name: "Money Split",
          matchName: "com.moneymoves.rgb-shift",
          parameters: {
            amount: 18,
            direction: 0,
            redOffset: 1,
            greenOffset: 0,
            blueOffset: -1,
            mix: 1,
            edgeBehavior: "mirror",
          },
        },
        {
          id: "vertical-punch",
          name: "Vertical Punch",
          matchName: "com.moneymoves.rgb-shift",
          parameters: {
            amount: 28,
            direction: 90,
            redOffset: 1,
            greenOffset: -0.35,
            blueOffset: -1,
            mix: 0.9,
            edgeBehavior: "wrap",
          },
        },
      ],
      schemaVersion: SCHEMA_VERSION,
    },
    {
      id: "halftone",
      name: "Halftone",
      matchName: "com.moneymoves.halftone",
      category: "palette",
      status: "available",
      description:
        "Print-style dots, squares, or lines with MoneyMoves palettes.",
      parameters: [
        {
          key: "cellSize",
          label: "Cell size",
          index: 1,
          type: "number",
          defaultValue: 8,
          min: 1,
          max: 256,
          step: 0.5,
          unit: "pixels",
          keyframeable: true,
        },
        {
          key: "angle",
          label: "Angle",
          index: 2,
          type: "number",
          defaultValue: 45,
          min: 0,
          max: 360,
          step: 1,
          unit: "degrees",
          keyframeable: true,
        },
        {
          key: "dotShape",
          label: "Dot shape",
          index: 3,
          type: "select",
          defaultValue: 1,
          options: [
            { id: "circle", label: "Circle", value: 1 },
            { id: "square", label: "Square", value: 2 },
            { id: "line", label: "Line", value: 3 },
          ],
          keyframeable: false,
        },
        {
          key: "contrast",
          label: "Contrast",
          index: 4,
          type: "number",
          defaultValue: 1.25,
          min: 0,
          max: 4,
          step: 0.05,
          keyframeable: true,
        },
        {
          key: "palette",
          label: "Palette",
          index: 5,
          type: "select",
          defaultValue: 2,
          options: [
            { id: "custom", label: "Custom", value: 1 },
            {
              id: "moneymoves-core",
              label: "MoneyMoves Core",
              value: 2,
            },
            { id: "editorial-mono", label: "Editorial Mono", value: 3 },
            { id: "signal-blue", label: "Signal Blue", value: 4 },
            { id: "terminal", label: "Terminal", value: 5 },
            { id: "phosphor", label: "Phosphor", value: 6 },
            { id: "amber", label: "Amber", value: 7 },
            { id: "paper", label: "Paper", value: 8 },
          ],
          keyframeable: false,
        },
        {
          key: "foreground",
          label: "Foreground",
          index: 6,
          type: "color",
          defaultValue: "#FF2448",
          keyframeable: true,
        },
        {
          key: "background",
          label: "Background",
          index: 7,
          type: "color",
          defaultValue: "#FFF6D8",
          keyframeable: true,
        },
        {
          key: "invert",
          label: "Invert",
          index: 8,
          type: "boolean",
          defaultValue: false,
          keyframeable: true,
        },
        {
          key: "mix",
          label: "Mix",
          index: 9,
          type: "number",
          defaultValue: 1,
          min: 0,
          max: 1,
          step: 0.01,
          unit: "percent",
          keyframeable: true,
        },
      ],
      presets: [
        {
          id: "money-dots",
          name: "Money Dots",
          matchName: "com.moneymoves.halftone",
          parameters: {
            cellSize: 8,
            angle: 45,
            dotShape: "circle",
            contrast: 1.25,
            palette: "moneymoves-core",
            invert: false,
            mix: 1,
          },
        },
        {
          id: "editorial-print",
          name: "Editorial Print",
          matchName: "com.moneymoves.halftone",
          parameters: {
            cellSize: 6,
            angle: 15,
            dotShape: "square",
            contrast: 1.5,
            palette: "editorial-mono",
            invert: false,
            mix: 0.9,
          },
        },
        {
          id: "terminal-lines",
          name: "Terminal Lines",
          matchName: "com.moneymoves.halftone",
          parameters: {
            cellSize: 10,
            angle: 0,
            dotShape: "line",
            contrast: 1.8,
            palette: "terminal",
            invert: false,
            mix: 1,
          },
        },
      ],
      schemaVersion: SCHEMA_VERSION,
    },
    {
      id: "dot-matrix",
      name: "Dot Matrix",
      matchName: "com.moneymoves.dot-matrix",
      category: "palette",
      status: "available",
      description:
        "Luminance-driven LED dots with branded or custom two-color palettes.",
      parameters: [
        {
          key: "spacing",
          label: "Spacing",
          index: 1,
          type: "number",
          defaultValue: 9,
          min: 1,
          max: 256,
          step: 0.5,
          unit: "pixels",
          keyframeable: true,
        },
        {
          key: "dotSize",
          label: "Dot size",
          index: 2,
          type: "number",
          defaultValue: 7,
          min: 0,
          max: 256,
          step: 0.5,
          unit: "pixels",
          keyframeable: true,
        },
        {
          key: "softness",
          label: "Softness",
          index: 3,
          type: "number",
          defaultValue: 0.6,
          min: 0.001,
          max: 64,
          step: 0.05,
          unit: "pixels",
          keyframeable: true,
        },
        {
          key: "angle",
          label: "Angle",
          index: 4,
          type: "number",
          defaultValue: 0,
          min: 0,
          max: 360,
          step: 1,
          unit: "degrees",
          keyframeable: true,
        },
        {
          key: "palette",
          label: "Palette",
          index: 5,
          type: "select",
          defaultValue: 2,
          options: [
            { id: "custom", label: "Custom", value: 1 },
            {
              id: "moneymoves-core",
              label: "MoneyMoves Core",
              value: 2,
            },
            { id: "editorial-mono", label: "Editorial Mono", value: 3 },
            { id: "signal-blue", label: "Signal Blue", value: 4 },
            { id: "terminal", label: "Terminal", value: 5 },
            { id: "phosphor", label: "Phosphor", value: 6 },
            { id: "amber", label: "Amber", value: 7 },
            { id: "paper", label: "Paper", value: 8 },
          ],
          keyframeable: false,
        },
        {
          key: "foreground",
          label: "Dot color",
          index: 6,
          type: "color",
          defaultValue: "#FF2448",
          keyframeable: true,
        },
        {
          key: "background",
          label: "Background",
          index: 7,
          type: "color",
          defaultValue: "#0B0B70",
          keyframeable: true,
        },
        {
          key: "mix",
          label: "Mix",
          index: 8,
          type: "number",
          defaultValue: 1,
          min: 0,
          max: 1,
          step: 0.01,
          unit: "percent",
          keyframeable: true,
        },
      ],
      presets: [
        {
          id: "money-led",
          name: "Money LED",
          matchName: "com.moneymoves.dot-matrix",
          parameters: {
            spacing: 9,
            dotSize: 7,
            softness: 0.6,
            angle: 0,
            palette: "moneymoves-core",
            mix: 1,
          },
        },
        {
          id: "terminal-board",
          name: "Terminal Board",
          matchName: "com.moneymoves.dot-matrix",
          parameters: {
            spacing: 12,
            dotSize: 9,
            softness: 0.35,
            angle: 0,
            palette: "terminal",
            mix: 1,
          },
        },
        {
          id: "diagonal-display",
          name: "Diagonal Display",
          matchName: "com.moneymoves.dot-matrix",
          parameters: {
            spacing: 7,
            dotSize: 6,
            softness: 1.2,
            angle: 45,
            palette: "signal-blue",
            mix: 0.9,
          },
        },
      ],
      schemaVersion: SCHEMA_VERSION,
    },
    {
      id: "eight-bit",
      name: "8-bit",
      matchName: "com.moneymoves.eight-bit",
      category: "palette",
      status: "available",
      description:
        "Pixel blocks with perceptual OKLab quantization into 2–8 colors.",
      parameters: [
        {
          key: "pixelSize",
          label: "Pixel size",
          index: 1,
          type: "number",
          defaultValue: 8,
          min: 1,
          max: 256,
          step: 1,
          unit: "pixels",
          keyframeable: true,
        },
        {
          key: "colorCount",
          label: "Color count",
          index: 2,
          type: "number",
          defaultValue: 6,
          min: 2,
          max: 8,
          step: 1,
          keyframeable: true,
        },
        {
          key: "palette",
          label: "Palette",
          index: 3,
          type: "select",
          defaultValue: 2,
          options: [...EFFECT_PALETTE_OPTIONS],
          keyframeable: false,
        },
        {
          key: "quantization",
          label: "Quantization",
          index: 4,
          type: "number",
          defaultValue: 1,
          min: 0,
          max: 1,
          step: 0.01,
          unit: "percent",
          keyframeable: true,
        },
        ...EIGHT_BIT_COLOR_DEFAULTS.map((defaultValue, colorIndex) => ({
          key: `color${colorIndex + 1}`,
          label: `Color ${colorIndex + 1}`,
          index: colorIndex + 5,
          type: "color" as const,
          defaultValue,
          keyframeable: true,
        })),
        {
          key: "mix",
          label: "Mix",
          index: 13,
          type: "number",
          defaultValue: 1,
          min: 0,
          max: 1,
          step: 0.01,
          unit: "percent",
          keyframeable: true,
        },
      ],
      presets: [
        {
          id: "money-console",
          name: "Money Console",
          matchName: "com.moneymoves.eight-bit",
          parameters: {
            pixelSize: 8,
            colorCount: 6,
            palette: "moneymoves-core",
            quantization: 1,
            mix: 1,
          },
        },
        {
          id: "terminal-4",
          name: "Terminal 4",
          matchName: "com.moneymoves.eight-bit",
          parameters: {
            pixelSize: 10,
            colorCount: 4,
            palette: "terminal",
            quantization: 1,
            mix: 1,
          },
        },
        {
          id: "soft-pixel",
          name: "Soft Pixel",
          matchName: "com.moneymoves.eight-bit",
          parameters: {
            pixelSize: 6,
            colorCount: 8,
            palette: "signal-blue",
            quantization: 0.65,
            mix: 0.85,
          },
        },
      ],
      schemaVersion: SCHEMA_VERSION,
    },
    {
      id: "dither",
      name: "Dither",
      matchName: "com.moneymoves.dither",
      category: "palette",
      status: "available",
      description:
        "Ordered Bayer or deterministic blue-noise dithering with 2–8 colors.",
      parameters: [
        {
          key: "mode",
          label: "Mode",
          index: 1,
          type: "select",
          defaultValue: 2,
          options: [
            { id: "bayer-2", label: "Bayer 2×2", value: 1 },
            { id: "bayer-4", label: "Bayer 4×4", value: 2 },
            { id: "bayer-8", label: "Bayer 8×8", value: 3 },
            { id: "blue-noise", label: "Blue Noise", value: 4 },
          ],
          keyframeable: false,
        },
        {
          key: "scale",
          label: "Scale",
          index: 2,
          type: "number",
          defaultValue: 1,
          min: 1,
          max: 64,
          step: 1,
          keyframeable: true,
        },
        {
          key: "colorCount",
          label: "Color count",
          index: 3,
          type: "number",
          defaultValue: 4,
          min: 2,
          max: 8,
          step: 1,
          keyframeable: true,
        },
        {
          key: "palette",
          label: "Palette",
          index: 4,
          type: "select",
          defaultValue: 2,
          options: [...EFFECT_PALETTE_OPTIONS],
          keyframeable: false,
        },
        {
          key: "threshold",
          label: "Threshold",
          index: 5,
          type: "number",
          defaultValue: 0,
          min: -1,
          max: 1,
          step: 0.01,
          keyframeable: true,
        },
        {
          key: "strength",
          label: "Strength",
          index: 6,
          type: "number",
          defaultValue: 0.75,
          min: 0,
          max: 1,
          step: 0.01,
          unit: "percent",
          keyframeable: true,
        },
        ...EIGHT_BIT_COLOR_DEFAULTS.map((defaultValue, colorIndex) => ({
          key: `color${colorIndex + 1}`,
          label: `Color ${colorIndex + 1}`,
          index: colorIndex + 7,
          type: "color" as const,
          defaultValue,
          keyframeable: true,
        })),
        {
          key: "mix",
          label: "Mix",
          index: 15,
          type: "number",
          defaultValue: 1,
          min: 0,
          max: 1,
          step: 0.01,
          unit: "percent",
          keyframeable: true,
        },
      ],
      presets: [
        {
          id: "money-bayer",
          name: "Money Bayer",
          matchName: "com.moneymoves.dither",
          parameters: {
            mode: "bayer-4",
            scale: 1,
            colorCount: 4,
            palette: "moneymoves-core",
            threshold: 0,
            strength: 0.75,
            mix: 1,
          },
        },
        {
          id: "editorial-coarse",
          name: "Editorial Coarse",
          matchName: "com.moneymoves.dither",
          parameters: {
            mode: "bayer-8",
            scale: 2,
            colorCount: 4,
            palette: "editorial-mono",
            threshold: 0.05,
            strength: 1,
            mix: 1,
          },
        },
        {
          id: "signal-noise",
          name: "Signal Noise",
          matchName: "com.moneymoves.dither",
          parameters: {
            mode: "blue-noise",
            scale: 1,
            colorCount: 5,
            palette: "signal-blue",
            threshold: 0,
            strength: 0.85,
            mix: 0.9,
          },
        },
      ],
      schemaVersion: SCHEMA_VERSION,
    },
    {
      id: "chromatic-aberration",
      name: "Chromatic Aberration",
      matchName: "com.moneymoves.chromatic-aberration",
      category: "stylize",
      status: "available",
      description:
        "Radial red/blue lens separation with an adjustable optical center.",
      parameters: [
        {
          key: "amount",
          label: "Amount",
          index: 1,
          type: "number",
          defaultValue: 18,
          min: 0,
          max: 200,
          step: 1,
          unit: "pixels",
          keyframeable: true,
        },
        {
          key: "centerX",
          label: "Center X",
          index: 2,
          type: "number",
          defaultValue: 0.5,
          min: 0,
          max: 1,
          step: 0.01,
          unit: "percent",
          keyframeable: true,
        },
        {
          key: "centerY",
          label: "Center Y",
          index: 3,
          type: "number",
          defaultValue: 0.5,
          min: 0,
          max: 1,
          step: 0.01,
          unit: "percent",
          keyframeable: true,
        },
        {
          key: "falloff",
          label: "Falloff",
          index: 4,
          type: "number",
          defaultValue: 1.25,
          min: 0.1,
          max: 4,
          step: 0.05,
          keyframeable: true,
        },
        {
          key: "edgeBehavior",
          label: "Edges",
          index: 5,
          type: "select",
          defaultValue: 1,
          options: [
            { id: "clamp", label: "Clamp", value: 1 },
            { id: "mirror", label: "Mirror", value: 2 },
            { id: "wrap", label: "Wrap", value: 3 },
          ],
          keyframeable: false,
        },
        {
          key: "mix",
          label: "Mix",
          index: 6,
          type: "number",
          defaultValue: 1,
          min: 0,
          max: 1,
          step: 0.01,
          unit: "percent",
          keyframeable: true,
        },
      ],
      presets: [
        {
          id: "subtle-lens",
          name: "Subtle Lens",
          matchName: "com.moneymoves.chromatic-aberration",
          parameters: {
            amount: 6,
            centerX: 0.5,
            centerY: 0.5,
            falloff: 1.5,
            edgeBehavior: "clamp",
            mix: 0.55,
          },
        },
        {
          id: "edge-split",
          name: "Edge Split",
          matchName: "com.moneymoves.chromatic-aberration",
          parameters: {
            amount: 22,
            centerX: 0.5,
            centerY: 0.5,
            falloff: 1.1,
            edgeBehavior: "mirror",
            mix: 1,
          },
        },
        {
          id: "wide-punch",
          name: "Wide Punch",
          matchName: "com.moneymoves.chromatic-aberration",
          parameters: {
            amount: 45,
            centerX: 0.48,
            centerY: 0.55,
            falloff: 0.75,
            edgeBehavior: "wrap",
            mix: 0.85,
          },
        },
      ],
      schemaVersion: SCHEMA_VERSION,
    },
    {
      id: "barrel-blur",
      name: "Barrel Blur",
      matchName: "com.moneymoves.barrel-blur",
      category: "stylize",
      status: "available",
      description:
        "Barrel or pincushion distortion with radial edge blur and quality modes.",
      parameters: [
        {
          key: "distortion",
          label: "Distortion",
          index: 1,
          type: "number",
          defaultValue: 0.25,
          min: -1,
          max: 1,
          step: 0.01,
          keyframeable: true,
        },
        {
          key: "blurRadius",
          label: "Blur radius",
          index: 2,
          type: "number",
          defaultValue: 8,
          min: 0,
          max: 128,
          step: 1,
          unit: "pixels",
          keyframeable: true,
        },
        {
          key: "centerX",
          label: "Center X",
          index: 3,
          type: "number",
          defaultValue: 0.5,
          min: 0,
          max: 1,
          step: 0.01,
          unit: "percent",
          keyframeable: true,
        },
        {
          key: "centerY",
          label: "Center Y",
          index: 4,
          type: "number",
          defaultValue: 0.5,
          min: 0,
          max: 1,
          step: 0.01,
          unit: "percent",
          keyframeable: true,
        },
        {
          key: "falloff",
          label: "Falloff",
          index: 5,
          type: "number",
          defaultValue: 1.5,
          min: 0.1,
          max: 4,
          step: 0.05,
          keyframeable: true,
        },
        {
          key: "quality",
          label: "Quality",
          index: 6,
          type: "select",
          defaultValue: 2,
          options: [
            { id: "draft", label: "Draft · 4 samples", value: 1 },
            { id: "standard", label: "Standard · 8 samples", value: 2 },
            { id: "high", label: "High · 16 samples", value: 3 },
          ],
          keyframeable: false,
        },
        {
          key: "edgeBehavior",
          label: "Edges",
          index: 7,
          type: "select",
          defaultValue: 1,
          options: [
            { id: "clamp", label: "Clamp", value: 1 },
            { id: "mirror", label: "Mirror", value: 2 },
            { id: "wrap", label: "Wrap", value: 3 },
          ],
          keyframeable: false,
        },
        {
          key: "mix",
          label: "Mix",
          index: 8,
          type: "number",
          defaultValue: 1,
          min: 0,
          max: 1,
          step: 0.01,
          unit: "percent",
          keyframeable: true,
        },
      ],
      presets: [
        {
          id: "soft-lens",
          name: "Soft Lens",
          matchName: "com.moneymoves.barrel-blur",
          parameters: {
            distortion: 0.12,
            blurRadius: 6,
            falloff: 1.75,
            quality: "standard",
            edgeBehavior: "mirror",
            mix: 0.7,
          },
        },
        {
          id: "barrel-punch",
          name: "Barrel Punch",
          matchName: "com.moneymoves.barrel-blur",
          parameters: {
            distortion: 0.5,
            blurRadius: 18,
            falloff: 1.1,
            quality: "high",
            edgeBehavior: "mirror",
            mix: 1,
          },
        },
        {
          id: "pincushion-rush",
          name: "Pincushion Rush",
          matchName: "com.moneymoves.barrel-blur",
          parameters: {
            distortion: -0.45,
            blurRadius: 28,
            falloff: 0.8,
            quality: "high",
            edgeBehavior: "wrap",
            mix: 0.9,
          },
        },
      ],
      schemaVersion: SCHEMA_VERSION,
    },
    {
      id: "bloom",
      name: "Bloom",
      matchName: "com.moneymoves.bloom",
      category: "stylize",
      status: "available",
      description:
        "Thresholded highlight glow with tint, soft knee, radius, and quality controls.",
      parameters: [
        {
          key: "threshold",
          label: "Threshold",
          index: 1,
          type: "number",
          defaultValue: 0.7,
          min: 0,
          max: 2,
          step: 0.01,
          keyframeable: true,
        },
        {
          key: "knee",
          label: "Soft knee",
          index: 2,
          type: "number",
          defaultValue: 0.2,
          min: 0,
          max: 1,
          step: 0.01,
          keyframeable: true,
        },
        {
          key: "radius",
          label: "Radius",
          index: 3,
          type: "number",
          defaultValue: 20,
          min: 0,
          max: 128,
          step: 1,
          unit: "pixels",
          keyframeable: true,
        },
        {
          key: "intensity",
          label: "Intensity",
          index: 4,
          type: "number",
          defaultValue: 0.8,
          min: 0,
          max: 4,
          step: 0.01,
          keyframeable: true,
        },
        {
          key: "tint",
          label: "Tint",
          index: 5,
          type: "color",
          defaultValue: "#FFE6CC",
          keyframeable: true,
        },
        {
          key: "quality",
          label: "Quality",
          index: 6,
          type: "select",
          defaultValue: 2,
          options: [
            { id: "draft", label: "Draft · 4 samples", value: 1 },
            { id: "standard", label: "Standard · 8 samples", value: 2 },
            { id: "high", label: "High · 16 samples", value: 3 },
          ],
          keyframeable: false,
        },
        {
          key: "mix",
          label: "Mix",
          index: 7,
          type: "number",
          defaultValue: 1,
          min: 0,
          max: 1,
          step: 0.01,
          unit: "percent",
          keyframeable: true,
        },
      ],
      presets: [
        {
          id: "warm-highlight",
          name: "Warm Highlight",
          matchName: "com.moneymoves.bloom",
          parameters: {
            threshold: 0.72,
            knee: 0.2,
            radius: 18,
            intensity: 0.7,
            tint: "#FFE6CC",
            quality: "standard",
            mix: 1,
          },
        },
        {
          id: "money-glow",
          name: "Money Glow",
          matchName: "com.moneymoves.bloom",
          parameters: {
            threshold: 0.55,
            knee: 0.3,
            radius: 32,
            intensity: 1.25,
            tint: "#FF2448",
            quality: "high",
            mix: 0.9,
          },
        },
        {
          id: "signal-bloom",
          name: "Signal Bloom",
          matchName: "com.moneymoves.bloom",
          parameters: {
            threshold: 0.62,
            knee: 0.18,
            radius: 26,
            intensity: 1,
            tint: "#3D8BFF",
            quality: "high",
            mix: 0.85,
          },
        },
      ],
      schemaVersion: SCHEMA_VERSION,
    },
    {
      id: "progressive-blur",
      name: "Progressive Blur",
      matchName: "com.moneymoves.progressive-blur",
      category: "stylize",
      status: "available",
      description:
        "Gradient-masked blur with direction, range, feather, inversion, and quality controls.",
      parameters: [
        {
          key: "strength",
          label: "Strength",
          index: 1,
          type: "number",
          defaultValue: 24,
          min: 0,
          max: 128,
          step: 1,
          unit: "pixels",
          keyframeable: true,
        },
        {
          key: "direction",
          label: "Direction",
          index: 2,
          type: "number",
          defaultValue: 90,
          min: -180,
          max: 180,
          step: 1,
          unit: "degrees",
          keyframeable: true,
        },
        {
          key: "start",
          label: "Start",
          index: 3,
          type: "number",
          defaultValue: 0.2,
          min: 0,
          max: 1,
          step: 0.01,
          unit: "percent",
          keyframeable: true,
        },
        {
          key: "end",
          label: "End",
          index: 4,
          type: "number",
          defaultValue: 0.8,
          min: 0,
          max: 1,
          step: 0.01,
          unit: "percent",
          keyframeable: true,
        },
        {
          key: "feather",
          label: "Feather",
          index: 5,
          type: "number",
          defaultValue: 1,
          min: 0,
          max: 1,
          step: 0.01,
          unit: "percent",
          keyframeable: true,
        },
        {
          key: "invert",
          label: "Invert",
          index: 6,
          type: "boolean",
          defaultValue: false,
          keyframeable: true,
        },
        {
          key: "quality",
          label: "Quality",
          index: 7,
          type: "select",
          defaultValue: 2,
          options: [
            { id: "draft", label: "Draft · 4 samples", value: 1 },
            { id: "standard", label: "Standard · 8 samples", value: 2 },
            { id: "high", label: "High · 16 samples", value: 3 },
          ],
          keyframeable: false,
        },
        {
          key: "mix",
          label: "Mix",
          index: 8,
          type: "number",
          defaultValue: 1,
          min: 0,
          max: 1,
          step: 0.01,
          unit: "percent",
          keyframeable: true,
        },
      ],
      presets: [
        {
          id: "soft-gradient",
          name: "Soft Gradient",
          matchName: "com.moneymoves.progressive-blur",
          parameters: {
            strength: 18,
            direction: 90,
            start: 0.2,
            end: 0.8,
            feather: 1,
            invert: false,
            quality: "standard",
            mix: 0.8,
          },
        },
        {
          id: "focus-falloff",
          name: "Focus Falloff",
          matchName: "com.moneymoves.progressive-blur",
          parameters: {
            strength: 48,
            direction: 90,
            start: 0.35,
            end: 0.62,
            feather: 1,
            invert: false,
            quality: "high",
            mix: 1,
          },
        },
        {
          id: "reverse-rush",
          name: "Reverse Rush",
          matchName: "com.moneymoves.progressive-blur",
          parameters: {
            strength: 64,
            direction: 0,
            start: 0.15,
            end: 0.75,
            feather: 0.7,
            invert: true,
            quality: "high",
            mix: 1,
          },
        },
      ],
      schemaVersion: SCHEMA_VERSION,
    },
    {
      id: "crt",
      name: "CRT",
      matchName: "com.moneymoves.crt",
      category: "stylize",
      status: "available",
      description:
        "Curved phosphor display with RGB convergence, scanlines, grain, flicker, vignette, and glow.",
      parameters: [
        {
          key: "curvature",
          label: "Curvature",
          index: 1,
          type: "number",
          defaultValue: 0.12,
          min: 0,
          max: 0.5,
          step: 0.01,
          unit: "percent",
          keyframeable: true,
        },
        {
          key: "scanlines",
          label: "Scanlines",
          index: 2,
          type: "number",
          defaultValue: 0.35,
          min: 0,
          max: 1,
          step: 0.01,
          unit: "percent",
          keyframeable: true,
        },
        {
          key: "phosphorMask",
          label: "Phosphor mask",
          index: 3,
          type: "number",
          defaultValue: 0.25,
          min: 0,
          max: 1,
          step: 0.01,
          unit: "percent",
          keyframeable: true,
        },
        {
          key: "convergence",
          label: "Convergence",
          index: 4,
          type: "number",
          defaultValue: 1.5,
          min: 0,
          max: 12,
          step: 0.1,
          unit: "pixels",
          keyframeable: true,
        },
        {
          key: "noise",
          label: "Noise",
          index: 5,
          type: "number",
          defaultValue: 0.06,
          min: 0,
          max: 1,
          step: 0.01,
          unit: "percent",
          keyframeable: true,
        },
        {
          key: "flicker",
          label: "Flicker",
          index: 6,
          type: "number",
          defaultValue: 0.08,
          min: 0,
          max: 1,
          step: 0.01,
          unit: "percent",
          keyframeable: true,
        },
        {
          key: "vignette",
          label: "Vignette",
          index: 7,
          type: "number",
          defaultValue: 0.4,
          min: 0,
          max: 1,
          step: 0.01,
          unit: "percent",
          keyframeable: true,
        },
        {
          key: "bloom",
          label: "Bloom",
          index: 8,
          type: "number",
          defaultValue: 0.25,
          min: 0,
          max: 2,
          step: 0.01,
          keyframeable: true,
        },
        {
          key: "mix",
          label: "Mix",
          index: 9,
          type: "number",
          defaultValue: 1,
          min: 0,
          max: 1,
          step: 0.01,
          unit: "percent",
          keyframeable: true,
        },
      ],
      presets: [
        {
          id: "clean-monitor",
          name: "Clean Monitor",
          matchName: "com.moneymoves.crt",
          parameters: {
            curvature: 0.06,
            scanlines: 0.18,
            phosphorMask: 0.12,
            convergence: 0.5,
            noise: 0.01,
            flicker: 0,
            vignette: 0.2,
            bloom: 0.15,
            mix: 0.7,
          },
        },
        {
          id: "money-crt",
          name: "Money CRT",
          matchName: "com.moneymoves.crt",
          parameters: {
            curvature: 0.12,
            scanlines: 0.35,
            phosphorMask: 0.25,
            convergence: 1.5,
            noise: 0.06,
            flicker: 0.08,
            vignette: 0.4,
            bloom: 0.25,
            mix: 1,
          },
        },
        {
          id: "broken-signal",
          name: "Broken Signal",
          matchName: "com.moneymoves.crt",
          parameters: {
            curvature: 0.18,
            scanlines: 0.65,
            phosphorMask: 0.55,
            convergence: 5,
            noise: 0.35,
            flicker: 0.4,
            vignette: 0.65,
            bloom: 0.6,
            mix: 1,
          },
        },
      ],
      schemaVersion: SCHEMA_VERSION,
    },
    {
      id: "ascii",
      name: "ASCII",
      matchName: "com.moneymoves.ascii",
      category: "palette",
      status: "available",
      description:
        "Real-time procedural character cells with six glyph families and source, mono, or palette color.",
      parameters: [
        {
          key: "cellSize",
          label: "Cell size",
          index: 1,
          type: "number",
          defaultValue: 12,
          min: 4,
          max: 64,
          step: 1,
          unit: "pixels",
          keyframeable: true,
        },
        {
          key: "charset",
          label: "Character family",
          index: 2,
          type: "select",
          defaultValue: 1,
          options: [
            { id: "standard", label: "Standard · . + # @", value: 1 },
            { id: "block", label: "Block", value: 2 },
            { id: "dot", label: "Dot", value: 3 },
            { id: "binary", label: "Binary · 0 / 1", value: 4 },
            { id: "shade", label: "Shade", value: 5 },
            { id: "braille", label: "Braille", value: 6 },
          ],
          keyframeable: false,
        },
        {
          key: "glyphContrast",
          label: "Glyph contrast",
          index: 3,
          type: "number",
          defaultValue: 1.2,
          min: 0,
          max: 4,
          step: 0.01,
          keyframeable: true,
        },
        {
          key: "invert",
          label: "Invert",
          index: 4,
          type: "boolean",
          defaultValue: false,
          keyframeable: true,
        },
        {
          key: "colorMode",
          label: "Color mode",
          index: 5,
          type: "select",
          defaultValue: 1,
          options: [
            { id: "source", label: "Source", value: 1 },
            { id: "mono", label: "Mono", value: 2 },
            { id: "palette", label: "Palette", value: 3 },
          ],
          keyframeable: false,
        },
        {
          key: "palette",
          label: "Palette",
          index: 6,
          type: "select",
          defaultValue: 2,
          options: [...EFFECT_PALETTE_OPTIONS],
          keyframeable: false,
        },
        {
          key: "foreground",
          label: "Foreground",
          index: 7,
          type: "color",
          defaultValue: "#FF2448",
          keyframeable: true,
        },
        {
          key: "background",
          label: "Background",
          index: 8,
          type: "color",
          defaultValue: "#0B0B16",
          keyframeable: true,
        },
        {
          key: "mix",
          label: "Mix",
          index: 9,
          type: "number",
          defaultValue: 1,
          min: 0,
          max: 1,
          step: 0.01,
          unit: "percent",
          keyframeable: true,
        },
      ],
      presets: [
        {
          id: "money-terminal",
          name: "Money Terminal",
          matchName: "com.moneymoves.ascii",
          parameters: {
            cellSize: 12,
            charset: "standard",
            glyphContrast: 1.25,
            invert: false,
            colorMode: "palette",
            palette: "terminal",
            mix: 1,
          },
        },
        {
          id: "source-glyphs",
          name: "Source Glyphs",
          matchName: "com.moneymoves.ascii",
          parameters: {
            cellSize: 10,
            charset: "braille",
            glyphContrast: 1.5,
            invert: false,
            colorMode: "source",
            palette: "custom",
            mix: 0.9,
          },
        },
        {
          id: "binary-signal",
          name: "Binary Signal",
          matchName: "com.moneymoves.ascii",
          parameters: {
            cellSize: 14,
            charset: "binary",
            glyphContrast: 1.8,
            invert: false,
            colorMode: "palette",
            palette: "signal-blue",
            mix: 1,
          },
        },
      ],
      schemaVersion: SCHEMA_VERSION,
    },
    ...[
      ["linocut", "LinoCut", "advanced"],
      ["voxel", "Voxel", "advanced"],
      ["blob-tracking", "Blob Tracking", "advanced"],
    ].map(([id, name, category]) => ({
      id,
      name,
      matchName: `com.moneymoves.${id}`,
      category,
      status: "planned",
      description: "Scheduled for a later MoneyMoves production phase.",
      parameters: [],
      presets: [],
      schemaVersion: SCHEMA_VERSION,
    })),
  ]);

export const EFFECTS = EFFECT_REGISTRY.map(
  ({ name, matchName }) => [name, matchName] as const,
);

export function getEffectDefinition(
  matchName: string,
): EffectDefinition | undefined {
  return EFFECT_REGISTRY.find((effect) => effect.matchName === matchName);
}
