[package]
name = "moneymoves-barrel-blur"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true
build = "build.rs"

[lib]
crate-type = ["cdylib"]

[package.metadata.prgpu]
match-name = "com.moneymoves.barrel-blur"
display-name = "MoneyMoves Barrel Blur"
category = "MoneyMoves"
support-url = "https://github.com/davidgajdamaka/moneymoves-plugin-set"
gpu = true
expansion = false

[dependencies]
after-effects.workspace = true
bytemuck.workspace = true
premiere.workspace = true
prgpu.workspace = true

[build-dependencies]
prgpu-build.workspace = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(catch_panics)", "cfg(does_dialog)", "cfg(with_premiere)", "cfg(threaded_rendering)"] }
